const $=s=>document.querySelector(s);
function makeDoc(type,project,notes){
 const lines=notes.split(/[.\n]+/).map(x=>x.trim()).filter(Boolean).slice(0,10);
 const date=new Date().toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'});
 const bullets=lines.map(x=>'• '+x).join('\n');
 if(type==='Client Progress Update') return `CLIENT PROGRESS UPDATE\n${project||'Project'}\nDate: ${date}\n\nCURRENT PROGRESS\n${bullets}\n\nNEXT STEPS\n• Confirm upcoming site activities and trade dates.\n• Confirm outstanding selections or approvals.\n• Issue the next progress update after review.\n\nACTION ITEMS\n• Project team: review and assign outstanding actions.\n• Client: confirm any required changes.\n\nBUILDFlow AI — draft for human review.`;
 if(type==='Site Meeting Minutes') return `SITE MEETING MINUTES\n${project||'Project'}\nDate: ${date}\n\nSITE NOTES\n${bullets}\n\nACTIONS\n1. Confirm owner for each outstanding item.\n2. Confirm agreed due dates.\n3. Record variations and approvals through the normal project process.\n\nBUILDFlow AI — draft for human review.`;
 if(type==='Scope of Work') return `DRAFT SCOPE OF WORK\n${project||'Project'}\nDate: ${date}\n\nWORKS\n${lines.map((x,i)=>(i+1)+'. '+x).join('\n')}\n\nGENERAL REQUIREMENTS\n• Coordinate with project drawings and specifications.\n• Confirm interfaces, dimensions and selections before work.\n• Document exclusions and variations separately.\n\nIMPORTANT: Check this administrative draft against the contract and project documentation before use.`;
 if(type==='Project Action List') return `PROJECT ACTION LIST\n${project||'Project'}\nDate: ${date}\n\nOPEN ITEMS\n${lines.map((x,i)=>(i+1)+'. '+x+' — Owner: TBC — Due: TBC').join('\n')}\n\nFOLLOW-UP\n• Assign owners and due dates.\n• Review open actions at the next meeting.`;
 return `QUOTE COMPARISON SUMMARY\n${project||'Project'}\nDate: ${date}\n\nSOURCE NOTES\n${bullets}\n\nCHECK\n• Confirm equivalent scope.\n• Review exclusions, allowances and provisional sums.\n• Compare lead times and validity periods.\n• Confirm GST treatment.\n• Record clarifications before a commercial decision.`;
}
$('#generate').onclick=()=>{const n=$('#notes').value.trim();if(!n){$('#output').textContent='Add project notes first.';return}$('#generate').textContent='Generating…';setTimeout(()=>{$('#output').textContent=makeDoc($('#type').value,$('#project').value.trim(),n);$('#generate').textContent='Generate with AI →'},350)};
$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#output').textContent);$('#copy').textContent='Copied';setTimeout(()=>$('#copy').textContent='Copy',1000)};
$('#leadForm').onsubmit=e=>{e.preventDefault();const lead={name:$('#name').value,email:$('#email').value,company:$('#company').value,need:$('#need').value,date:new Date().toISOString()};const arr=JSON.parse(localStorage.getItem('buildflow_leads')||'[]');arr.push(lead);localStorage.setItem('buildflow_leads',JSON.stringify(arr));$('#status').textContent='Enquiry saved. Connect a production email/backend before launch.';e.target.reset()};
$('#loginBtn').onclick=()=>$('#modal').classList.add('open');$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};
$('#demoLogin').onclick=()=>$('#loginStatus').textContent='Demo login: connect authentication to enable customer accounts.';
